version: "3.7"
services:
  gitlab-bot:
    image: stephaneklein/gitlab-bot:latest
    ports:
      - 8080:8080
    environment:
      GL_SECRET: ${GL_SECRET}
      GL_ACCESS_TOKEN: ${GL_ACCESS_TOKEN}
      GL_URL: ${GL_URL}
